# Generated by Django 5.0.3 on 2024-04-17 07:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HS', '0003_alter_documentupload_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='file_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
