# Generated by Django 5.0.3 on 2024-04-19 21:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HS', '0004_documentupload_file_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='file_identifier',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='file_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
