# Generated by Django 5.0.3 on 2024-04-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HS', '0005_alter_documentupload_file_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='file_identifier',
        ),
    ]
