# Generated by Django 5.0.3 on 2024-04-30 13:12

import HS.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HS', '0006_remove_documentupload_file_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='file_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='file_content',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['docx', 'pdf', 'xlsx', 'txt']), HS.models.validate_file_mimetype]),
        ),
    ]
