# Generated by Django 5.0.3 on 2024-06-15 12:26

import HS.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HS', '0009_alter_documentupload_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='file_content',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['docx', 'pdf', 'xlsx', 'txt', 'csv']), HS.models.validate_file_mimetype, HS.models.file_size_validator]),
        ),
    ]
