# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - marcorp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      

      - name: Check disk usage before setup
        run: df -h

      - name: Clean up before build
        run: sudo rm -rf /tmp/*

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: | 
          pip install -r requirements.txt --no-cache-dir
          cd RagApp/theme/static_src
          npm install

      - name: Build Tailwind CSS
        run: |
          python manage.py tailwind install
          python manage.py tailwind build


      - name: Run collectstatic
        run: python RagApp/manage.py collectstatic --noinput
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Make startup script executable
        run: chmod +x RagApp/startup.sh


      - name: Zip artifact for deployment
        run: zip -r release.zip  ./* -x "env/*" ".git/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

      - name: List contents of deployment package
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -R
          
    

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Check disk usage after deployment
        run: df -h

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A2347FC44CDC459E9C8375D845D93EED }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5555363E66394723A7AFC19A8F4E89E1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E007B6BF6DA649F0A11C7510359692AB }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'marcorp'
          slot-name: 'Production'
          package: .
        
      - name: Check disk usage after deployment
        run: df -h
